{{- if .Values.service.secrets.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-api-training.fullname" . }}-secret
  labels: {{- include "quarkus-api-training.labels" . | nindent 4 }}
type: Opaque
data:
  postgres.username: "{{ .Values.secret.postgresql.username | b64enc }}"
  postgres.password: "{{ .Values.secret.postgresql.password | b64enc }}"
---
{{- end }}
