{{- if .Values.service.secrets.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-api-training.fullname" . }}-secret
  labels: {{- include "quarkus-api-training.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $files := .Files }}
    {{ range $path, $bytes := .Files.Glob "secrets/**.dec.yaml" }}
    {{- $secretData := $files.Get $path | fromYaml }}
    {{- range $name, $secret := ($secretData) }}
    {{ $name }}: {{ $secret | b64enc }}
  {{- end }}
---
{{- end }}

{{- end }}
