apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payouts-liquibase-cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  serviceName: payouts-liquibase-cluster
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
      - name: postgres
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
