# see docs https://keda.sh/docs/2.6/scalers/prometheus/
# Enable scaler in valuse.yaml Set key: Values.keda.memory.enabled = true
{{- if .Values.keda.memory.enabled -}}
{{ if eq .Release.Namespace "production" }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "memory-scaledobject-{{ .Chart.Name }}-{{ .Release.Namespace }}"
  namespace: production
  labels:
    deploymentName: "memory-{{ .Chart.Name }}-{{ .Release.Namespace }}"
    {{- include "quarkus-api-training.labels" . | nindent 4 }}
spec:
  minReplicaCount: {{ .Values.keda.memory.minReplicaCount }}
  pollingInterval: {{ .Values.keda.memory.pollingInterval }}   # Optional. Default: 30 seconds
  cooldownPeriod: {{ .Values.keda.memory.cooldownPeriod }}   # Optional. Default: 300 seconds
  maxReplicaCount: {{ .Values.keda.memory.maxReplicaCount }}  # Optional. Default: 100
  scaleTargetRef:
    name: "{{ include "quarkus-api-training.fullname" . }}"
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "80"
{{ end }}
{{- end }}
