apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-on-kubernetes
  labels: 
    app.kubernetes.io/name: liquibase-on-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: liquibase-on-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: liquibase-on-kubernetes
    spec:
      initContainers:
      - env:
        - name: URL
          value: jdbc:postgresql://example-liquibase-cluster/quarkus?currentSchema=liquibase
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: quarkus-owner-user.example-liquibase-cluster.credentials.postgresql.acid.zalan.do
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: quarkus-owner-user.example-liquibase-cluster.credentials.postgresql.acid.zalan.do
              key: password
        name: liquibase-migration
        image: liquibase/liquibase:4.9
        args:
          - "--url=$(URL)" 
          - "--changeLogFile=db.changelog-master.yaml" 
          - "--username=$(USERNAME)"
          - "--password=$(PASSWORD)"
          - "--classpath=/liquibase/changelog"
          - "update"
          # - "--log-level=debug"
        resources:
          limits:
            cpu: "100m"
            memory: "500Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
        volumeMounts:
        - name: liquibase-volume
          mountPath: /liquibase/changelog
          readOnly: true
      volumes:
      - name: liquibase-volume
        projected:
          sources:
          - configMap:
              name: liquibase-on-kubernetes
              items:
              - key: db.changelog-master.yaml
                path: db.changelog-master.yaml
              - key: client.csv
                path: data/client.csv
              - key: service.csv
                path: data/service.csv
              - key: service_setting.csv
                path: data/service_setting.csv
      containers:
      - env:
        - name: QUARKUS_DATASOURCE_REACTIVE_URL
          value: postgresql://example-liquibase-cluster/quarkus
        - name: QUARKUS_HIBERNATE_ORM_DATABASE_DEFAULT_SCHEMA
          value: liquibase
        - name: QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE
          value: require
        - name: QUARKUS_DATASOURCE_REACTIVE_TRUST_ALL
          value: "true"
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: quarkus-owner-user.example-liquibase-cluster.credentials.postgresql.acid.zalan.do
              key: username
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quarkus-owner-user.example-liquibase-cluster.credentials.postgresql.acid.zalan.do
              key: password
        name: quarkus-app-api
        image: ghcr.io/juliuskrah/quarkus-liquibase
        imagePullPolicy: Always
        resources:
          limits:
            memory: "40Mi"
            cpu: "80m"
          requests:
            memory: "20Mi"
            cpu: "60m"
        ports:
        - containerPort: 8080
          name: http
 
