name: build-and-publish-docker-image
run-name: A job to run build and push docker image on ${{ github.repository }}; started by @${{ github.actor }}
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    uses: ./.github/workflows/unit-test-quarkus-reusable.yml
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0'
          cache: 'maven'
      - name: Build native image with Maven
        run: mvn package -Pnative -Dquarkus.native.container-build=true --file pom.xml
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          retention-days: 1
          path: |
            target
            !target/**/*.class
            !target/**/*.html
            !target/**/*.properties
            !target/**/*.jar

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:
      # - uses: actions/checkout@v3
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: actions/download-artifact@v3
        with:
          name: deployment-artifact
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          file: src/main/docker/Dockerfile.native-micro
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
