name: run-unit-tests
on: 
  push:
  release:
    types: ['published']
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17.0'
        cache: 'maven'
    - name: Unit test with Maven
      run: mvn test --file pom.xml
